try a catch err:
  | if x when Error: x
