try a catch err:
  | Error if x: x
